### ISSUE TITLE
What should next auth url be?

### ISSUE THREAD

**Issue by bisonbet** [gaiin-platform/amplify-genai-iac#12]
I have gotten through the directions with some changes, but when I look at the log of the docker on ECS - it's complaining:

	2024-07-02T18:16:44.756Z	⨯ TypeError [ERR_INVALID_URL]: Invalid URL
	2024-07-02T18:16:44.756Z	at new NodeError (node:internal/errors:399:5)
	2024-07-02T18:16:44.756Z	at new URL (node:internal/url:577:13)
	2024-07-02T18:16:44.756Z	at parseUrl (/app/node_modules/next-auth/utils/parse-url.js:17:16)
	2024-07-02T18:16:44.756Z	at Object.<anonymous> (/app/node_modules/next-auth/react/index.js:72:34)
	2024-07-02T18:16:44.756Z	at Module._compile (node:internal/modules/cjs/loader:1275:14)
	2024-07-02T18:16:44.756Z	at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
	2024-07-02T18:16:44.756Z	at Module.load (node:internal/modules/cjs/loader:1133:32)
	2024-07-02T18:16:44.756Z	at Module._load (node:internal/modules/cjs/loader:972:12)
	2024-07-02T18:16:44.756Z	at Module.require (node:internal/modules/cjs/loader:1157:19)
	2024-07-02T18:16:44.756Z	at mod.require (/app/node_modules/next/dist/server/require-hook.js:65:28) {
	2024-07-02T18:16:44.756Z	input: '',
	2024-07-02T18:16:44.756Z	code: 'ERR_INVALID_URL'
	2024-07-02T18:16:44.756Z    }

I believe if I'm reading this right, it's due to a lack of next-auth url.  Should this be the token signing key from cognito?  I'm weak on this stuff, and I wasn't sure how else to ask about it, so I apologize if this is the wrong place/way.

**Comment by karnsab** [comment]
It should be set to the web address that you are planning to use for the application. Ie, https://myaisite.com or whatever you’ve chosen as your domain name.
